In [7]:
import numpy as np

In [14]:
l = [1,2,3,4,5]                    #list
print(l)
a = np.array(l)                    #1D Array (list to array)
print(a)
l1 = [[1,2,3,4],[5,6,7,8]]         #list of lists
print(l1)
a1 = np.array(l1)                  #2D Array
print(a1)
np.zeros(5)                        #prints [0 0 0 0 0]
np.ones(5)                         #prints [1 1 1 1 1]
np.zeros((3,3))                    #prints 3*3 2D array of zeros

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
l1 = [range(5),range(4)]           #doesn't work donno why :(
a2 = np.array(l1)
print(a2)
a3 = np.arange(5)                  #arange is same as range but retruns array of [0 1 2 3 4]
print(a3)

[range(0, 5) range(0, 4)]
[0 1 2 3 4]


In [32]:
#Data type conversion

print(a3)
a4 = a3.astype(float)              #converts data type
print(a4)

print(a3.dtype)                          
print(a4.dtype)
print(a4.ndim)
print(a4.size)                     # Total number of elements
print(a4.shape)                    #axis 0 is rows, axis 1 is columns
print(len(a4))                     #returns size of first dim (rows)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]
int64
float64
1
5
(5,)
5


In [60]:
#Reshaping

a5 = np.arange(8)
print(a5)
print(a5.ndim)

a6 = a5.reshape(2,4)
print(a6)
print(a6.ndim)

a7 = a5.reshape(2,2,2)
print(a7)
print(a7.ndim)

#transpose
a8 = a6.T
print(a8)
print(a6.shape)                   #shape = (2,4)
print(a8.shape)                   #after Transpose, shape = (4,2)

#flatten array - converts into 1D Array
a9 = a7.flatten()
print(a9)
print(a7.ndim)
print(a9.ndim)

[0 1 2 3 4 5 6 7]
1
[[0 1 2 3]
 [4 5 6 7]]
2
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
(2, 4)
(4, 2)
[0 1 2 3 4 5 6 7]
3
1


In [10]:
#Indexing and Slicing (same as lists)   #start:stop:step - Slicing syntax

b = np.arange(10, dtype = float).reshape(2,5)
print(b)
print(b[0])                     #returns first row
print(b[0,0], b[0][0])          #both returns first element 0.0
print(b[-1])                    #returns last row

#Slicing

print(b[:,:])                   #returns all rows and columns
print(b[-1,-1])                 #returns the last element of last row

print(b[1:])                    #returns row index = 1 (Second row) till end
print(b[1,1:])                  #points to row index = 1 and starts from column index = 1 till end
print(b[:,3])                   #returns third column on both rows
print(b[-1])                    #returns last row

print(b[::-1])                  #reverses the array

#updatable
b[0,0] = 100
print(b)

#b[0,5]=100 immutable

#Boolean array indexing
b1 = b[b>5]
print(b1)

print(np.unique(b))           #prints unique value

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[0. 1. 2. 3. 4.]
0.0 0.0
[5. 6. 7. 8. 9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
9.0
[[5. 6. 7. 8. 9.]]
[6. 7. 8. 9.]
[3. 8.]
[5. 6. 7. 8. 9.]
[[5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4.]]
[[100.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]]
[100.   6.   7.   8.   9.]
[  1.   2.   3.   4.   5.   6.   7.   8.   9. 100.]


In [21]:
#array functions

c = np.arange(5)
print(c)

print(np.sqrt(c))
print(np.ceil(c))
print(np.isnan(c))

print(c.sum())
print(b.sum(axis=0))

print(np.random.rand(5))
print(np.random.rand(2,2))           #creates 2*2 array

[0 1 2 3 4]
[0.         1.         1.41421356 1.73205081 2.        ]
[0. 1. 2. 3. 4.]
[False False False False False]
10
[105.   7.   9.  11.  13.]
[0.48959719 0.75360015 0.13025934 0.90463061 0.02186233]
[[0.2252401  0.97573386]
 [0.73559719 0.36563463]]


In [22]:
c1 = np.array([[ 0,  0,  0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
c2 = np.array([0, 1, 2])

print(c1 + c2)           #The smaller array is stretched or “broadcasted” across the larger array so that they have compatible shapes.


[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [26]:
x = np.random.randn(4, 2)
print(x)

for i in x:
    for j in i:
        if 
        temp = 

[[ 1.26015355 -1.11387831]
 [-0.20498232 -1.76083695]
 [ 1.55775744 -0.89509604]
 [ 0.32445551  1.03972128]]
[ 1.26015355 -1.11387831]
[-0.20498232 -1.76083695]
[ 1.55775744 -0.89509604]
[0.32445551 1.03972128]
